import Head from 'next/head'
import React, {useContext, useEffect, useState} from 'react';
import ProductsList from '../components/productsComponents/ProductsList'
import axios from 'axios';
import {useDispatch} from 'react-redux'
import {login, logout} from '../reducers/userReducer'

export default function Home({products}) {
    const dispatch = useDispatch()

    useEffect(() => {
        if(localStorage.getItem("userId") !== null){
            axios.get(`/api/user/isLoggedIn`).then(res => {
                if(res.status === 200){
                    dispatch(login({
                        userEmail: localStorage.getItem("userEmail"),	
                        userPhone: localStorage.getItem("userPhone"),	
                        userId: localStorage.getItem("userId"),	
                        userName: localStorage.getItem("userName"),	
                        userJoinDate: localStorage.getItem("userJoinDate"),	
                        token:   localStorage.getItem("token"),	
                        userType: localStorage.getItem("userType")
                    }))
                } 
            }).catch(err => {
                dispatch(logout());
            });
        }
        else {
            dispatch(logout());
        }
    })

    return (
        <div>
        <Head>
            <title>Agro Chain</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="./icons8-agriculture-85.png" />
        </Head>

        <main>
            <ProductsList products={products} key={products.PRODUCT_ID}/>
        </main>

        <footer>
            
        </footer>
        </div>
    )
}

Home.getInitialProps = async () => {
    const response = await fetch("http://localhost:3000/api/products")
    let data = await response.json();
    return {products: data}
}