import Head from 'next/head'
import React, {useContext} from 'react';
import ProductsList from '../components/productsComponents/ProductsList'
// import {userContext} from '../ContextAPI/userDetailsConext'

export default function Home({products}) {
//   const {
//     token, setToken,
//     userId, setId,
//     userEmail, setEmail,
//     userName, setName,
//     userPhone, setPhone,
//     userType, setType,
//     userJoinDate, setJoinDate
// } = useContext(userContext);

// localStorage.getItem("userId")
    return (
        <div>
        <Head>
            <title>Agro Chain</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="./icons8-agriculture-85.png" />
        </Head>

        <main>
            <ProductsList products={products} key={products.PRODUCT_ID}/>
        </main>

        <footer>
            
        </footer>
        </div>
    )
}

Home.getInitialProps = async () => {
    const response = await fetch("http://localhost:3000/api/products")
    let data = await response.json();
    return {products: data}
}